### ISSUE TITLE
Some recipe/ lore suggestions

### ISSUE THREAD

**Issue by MyDeloreanWontStart** [T145/magistics#25]
Lil'fernal Furnace
 
"So hot, they'll melt your popsicle!"
 
"After climbing up the infernal furnace for the umpteenth time, you began to wonder if this was the most efficient way to smelt. Of course not. Research on the nature of the flame spirit that powers your furnace has been fruitful: you can now, theoretically, stuff it into a smaller receptacle. This won't be a happy situation for the creature, but at least you don't have to climb anymore."
 
Recipe: IF THAUMIC HORIZONS IS DETECTED: CREATURE INFUSION: blaze in vat, infused with 4 obsidian, 4 netherbrick, 1 lava bucket
        IF NOT DETECTED:Same thing, but with ember heart in middle (if automagy detected) or flint and steel if none.
 
-----------------------------------------------------------------------------------------------------------------------------------
 
Mask Of Cruelty
 
"Anyone say 'staring contest?'
 
"Only a maniac would construct a device of such pure evil that it burns the skin of whatever it gazes upon. Which means you were the perfect one to invent it. Though you do feel like it did exist very long ago...."
 
recipe: INFUSION: Goggles of revealing in middle, outside: eldritch gear, wither skull, 2 eyes of ender, 4 obsidian

**Comment by T145** [comment]
Well, for the "Lil'fernal Furnace," I already have something concocted that I call the Chthonian Furnace! It is basically an infernal furnace in one block, w/ some extra special features. Also, instead of creating a surplus of issues, if you could just put all of the lore on one text document on PasteBin for me to review and notify me in the previous issue, it would save both of us a lot of time! Thanks!

**Comment by MyDeloreanWontStart** [comment]
Okay, sorry.
