### ISSUE TITLE
still waiting for the hungry strongbox/COFH dependency/latest forge crash fix

### ISSUE THREAD

**Issue by trollworkout** [T145/magistics#46]
hopefully this gets fixed for the next update as I can't currently play this mod. I was forced to install the latest forge as a req for Erebus.

also the hungry strongbox has some COFH dependancy TSEBase or something . I'm hoping all dependencies on COFH can be optional in the future

**Comment by crunkazcanbe** [comment]
I will update this in the coming days dude keep a look out here ,and I will have a link :) I already have it updated to the latest forge as I did that last week just to get it working so I could once again play with it ,but I didn't know about the CoFH issue . I will fix the COFH dependency before I release a fix . I updated BigReactors a few days ago ,and posted a link to the new build on the BigReactor GitHub so If your into that mod go get that in the issue section of the BigReactor gitHub .

**Comment by T145** [comment]
I'm going to update the mod shortly. I had a tiny bit of free time before finals, so I thought I'd at least update the repo. Once Christmas break hits, there will be some more progress. :)

**Comment by T145** [comment]
@crunkazcanbe, if you want to work on something, go check out this: https://github.com/T145/hungrystorage

My first priority is getting something into the hands of players, and atm the hungry chests are the most complete part of the mod. Because of this, I'm going to move them into their own mod. I want to recruit some coders and texture makers to work on it to get it public ASAP. I kind of feel bad dangling Magistics in front of everyone for so long... but hey, at least it's not RedPower :smile:
