### ISSUE TITLE
One crash, and the state of Magistics at this point in time.

### ISSUE THREAD

**Issue by 63502** [T145/magistics#47]
What is the state of development on this mod at the moment? I have not seen any activity related to it on curseforge or github for some time now. I really like the concept, as I have played around with Thaumcraft 2 quite a bit, but unfortunately I have yet to be able to play the mod since my own set of mods is incompatible with this addon, and it hasn't been updated since early 2015.

 

Crash report link: [http://pastebin.com/PYu8Cgzx](http://pastebin.com/PYu8Cgzx) (same report at #45 )

(I doubt anything will happen at this point, but all the same, here it is)

**Comment by T145** [comment]
Ya, I've left the mod alone for a while since I'm currently a student in college, so I don't have much by way of free time. To be honest, I do need some help on this. Having some developers who could work on it would allow me to pop in and out of the project freely, adding new things and fixing bugs. Until then, it'll probably remain dormant.

**Comment by T145** [comment]
If you want something to play with, then I'd recommend [HungryStorage](http://www.curse.com/mc-mods/minecraft/239069-hungrystorage)

**Comment by 63502** [comment]
Ok, good to see that you are still here! :D 
I am also a college student, so I absolutely understand how that whole process goes.
I have no programming ability whatsoever, so I can't help you there, sorry. :( 
But I am glad you are actually still paying attention to this project, even though you don't have the time to work on it at present. I sincerely do hope you find the people you need.

On the note of finding people to help with the project, if you have the time, I would suggest updating the mod page on curseforge to include some big bold text at the very top that says something along the lines of DEVS WITH TIME ARE NEEDED HERE, PLEASE HELP. That would probably go quite a ways toward getting the extra support you need.

**Comment by 63502** [comment]
........................YOU'RE BACK!!!! XD

**Comment by T145** [comment]
Yep! Now just to rally up a team again! I've finally decided on a direction for the mod. One of the main reasons I haven't had much progress is because I keep thinking of new ideas and things to add, jumbling everything together and trying to maintain it. That hasn't seemed to work out, so now I have a plan. I'm going to add a bunch of handy vanilla tweaks to alter early-game interactions, and then ease into Thaumcraft steadily, having complete features ready before test builds. If you know anyone who's interested, let me know!

**Comment by 63502** [comment]
That's great to hear!

Out of curiosity, are you continuing development of the 1.7.10 version? Thaumcraft for 1.8.9 seems to be on hold what with Azanor releasing Baubles for 1.9.0, and at the moment lots of other people also seem to have shifted focus away from 1.8.9 and are either developing solely for 1.9, or are waiting for a stable forge version for 1.9.3+.

I'm just interested in where you stand.

**Comment by T145** [comment]
1.7.10 has the most stable environment, so I'll stick with it for now. Honestly the new TC doesn't seem to be as professionally crafted as the previous versions either, so waiting until both TC and the development environment it lies on to be more stable just seems logical. Also, there isn't that much of a push to update, since literally anything can be accomplished on the 1.7.10 end, while developing on the new versions requires a lot of unnecessary extra effort.

**Comment by 63502** [comment]
Yeah, I tend to hear that a lot about most things related to 1.8.9+. While I do like the new Thaumcraft for the Golemancy and easy pipe-less essentia movement, the aura and taint mechanics are just a pain to deal with.
