### ISSUE TITLE
[Question] Will there be a Thauminomicon Type Book?

### ISSUE THREAD

**Issue by MokahTGS** [T145/magistics#57]
Is there a book that give instructions how to do things or do you have something like that planned?

**Comment by T145** [comment]
Yes, there will be. Atm, I have it planned so that instead of having to gather an excess of useless artifacts around the world, one will instead gather research notes. Once these notes go through the process of yet-to-be-implemented research, the discoveries can be placed w/in the book to unlock new tabs of organization. It's kind of like how Azanor was planning TC6 research to be, except instead of there being multiple steps to research in a gui, it will be through my research system, and applying the research to a book will catalog it. Also, once a research has been completed, the recipe will be available for the whole world. I like to attribute this to word-of-mouth sharing, so the mechanic of copying and sharing notes is no longer needed.

**Comment by MokahTGS** [comment]
Alright, sounds great.  I don't know if I ever played TC2 so I'm not at all familiar with how it worked.
